# Generated by Django 4.1.2 on 2022-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_user_state_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
